# Generated by Django 5.2.4 on 2025-08-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cricketer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('batting_style', models.CharField(blank=True, max_length=100)),
                ('bowling_style', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
